var DEALS = [
  {
    "id": 1,
    "title": "Assos Mille GT Jersey C2 EVO Jersey",
    "category": "clothing",
    "priceNow": 19,
    "priceWas": 125,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/assos-mille-gt-jersey-c2-evo-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=240996&w=320&h=256"
  },
  {
    "id": 2,
    "title": "Assos Trail Jersey T3 W Jersey",
    "category": "clothing",
    "priceNow": 13,
    "priceWas": 90,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/assos-trail-womens-jersey-t3-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=240588&w=320&h=256"
  },
  {
    "id": 3,
    "title": "Sportful Supergiara W Jersey",
    "category": "clothing",
    "priceNow": 20,
    "priceWas": 100,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-supergiara-w-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=196251&w=320&h=256"
  },
  {
    "id": 4,
    "title": "Assos Trail LS Jersey T3 W Jersey",
    "category": "clothing",
    "priceNow": 24,
    "priceWas": 120,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/assos-trail-womens-ls-jersey-t3-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=240646&w=320&h=256"
  },
  {
    "id": 5,
    "title": "Sportful Tempo W Winter Jacket",
    "category": "clothing",
    "priceNow": 35,
    "priceWas": 170,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-tempo-w-2021-winter-jacket",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=237574&w=320&h=256"
  },
  {
    "id": 6,
    "title": "Sportful Vélodrome W Jersey",
    "category": "clothing",
    "priceNow": 18,
    "priceWas": 85,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-velodrome-w",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=211101&w=320&h=256"
  },
  {
    "id": 7,
    "title": "Sportful Monocrom W Jersey",
    "category": "clothing",
    "priceNow": 25,
    "priceWas": 100,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-monocrom-woman-cycling-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=211225&w=320&h=256"
  },
  {
    "id": 8,
    "title": "Sportful Evo W Jersey",
    "category": "clothing",
    "priceNow": 25,
    "priceWas": 100,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-evo-w",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=211095&w=320&h=256"
  },
  {
    "id": 9,
    "title": "Sportful Pro Dames Jersey Jersey",
    "category": "clothing",
    "priceNow": 25,
    "priceWas": 100,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-pro-dames-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=211199&w=320&h=256"
  },
  {
    "id": 10,
    "title": "Sportful Escape Supergiara W Jersey",
    "category": "clothing",
    "priceNow": 22,
    "priceWas": 90,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-escape-supergiara-w",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=211084&w=320&h=256"
  },
  {
    "id": 11,
    "title": "Sportful Flare W Jersey",
    "category": "clothing",
    "priceNow": 21,
    "priceWas": 85,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-flare-w",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=163698&w=320&h=256"
  },
  {
    "id": 12,
    "title": "Sportful Checkmate W Jersey",
    "category": "clothing",
    "priceNow": 19,
    "priceWas": 75,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/checkmate-w-sportful",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=211141&w=320&h=256"
  },
  {
    "id": 13,
    "title": "Sportful Vélodrome W Top",
    "category": "accessories",
    "priceNow": 15,
    "priceWas": 60,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-velodrome-w-top-top",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=213272&w=320&h=256"
  },
  {
    "id": 14,
    "title": "Assos GT C2 Cycling Socks",
    "category": "clothing",
    "priceNow": 6,
    "priceWas": 20,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/assos-gt-c2-cycling-socks",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=241797&w=320&h=256"
  },
  {
    "id": 15,
    "title": "Sportful SRK Winter Jacket",
    "category": "clothing",
    "priceNow": 88,
    "priceWas": 180,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-srk-jacket-winter-jacket",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=238774&w=320&h=256"
  },
  {
    "id": 16,
    "title": "Craft Core Essence W Jersey",
    "category": "clothing",
    "priceNow": 30,
    "priceWas": 60,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/craft-core-essence-w-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=201246&w=320&h=256"
  },
  {
    "id": 17,
    "title": "Rogelli Signature W Jersey",
    "category": "clothing",
    "priceNow": 45,
    "priceWas": 90,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/rogelli-signature-w-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=205743&w=320&h=256"
  },
  {
    "id": 18,
    "title": "Castelli Premio Evo Jersey",
    "category": "clothing",
    "priceNow": 110,
    "priceWas": 220,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/castelli-premio-evo-jersey-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=233240&w=320&h=256"
  },
  {
    "id": 19,
    "title": "Sidi Fast 2 Road Cycling Shoes",
    "category": "clothing",
    "priceNow": 96,
    "priceWas": 190,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sidi-fast-2",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=233057&w=320&h=256"
  },
  {
    "id": 20,
    "title": "Craft ADV Bike SubZ 2 Fietsjack Groen/Zwart Heren",
    "category": "bikes",
    "priceNow": 71,
    "priceWas": 140,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4199-001-N2509/medium/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren-1.webp"
  },
  {
    "id": 21,
    "title": "Craft ADV Bike SubZ 2 Fietsjack Groen/Zwart Heren",
    "category": "bikes",
    "priceNow": 71,
    "priceWas": 140,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4199-001-N2509/medium/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren-1.webp"
  },
  {
    "id": 22,
    "title": "Craft ADV Bike SubZ 2 Fietsjack Groen/Zwart Heren",
    "category": "bikes",
    "priceNow": 71,
    "priceWas": 140,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4199-001-N2509/medium/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren-1.webp"
  },
  {
    "id": 23,
    "title": "Craft ADV Bike SubZ 2 Fietsjack Groen/Zwart Heren",
    "category": "bikes",
    "priceNow": 71,
    "priceWas": 140,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4199-001-N2509/medium/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren-1.webp"
  },
  {
    "id": 24,
    "title": "Craft ADV Bike SubZ 2 Fietsjack Groen/Zwart Heren",
    "category": "bikes",
    "priceNow": 71,
    "priceWas": 140,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4199-001-N2509/medium/craft-adv-bike-subz-2-fietsjack-groen-zwart-heren-1.webp"
  },
  {
    "id": 25,
    "title": "Schwalbe Racing Ralph Addix Speed Super Ground TLE MTB Tyre",
    "category": "parts",
    "priceNow": 35,
    "priceWas": 69,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/schwalbe-racing-ralph-addix-speed-super-ground-tyre",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=216798&w=320&h=256"
  },
  {
    "id": 26,
    "title": "Schwalbe One TLE Road Bike Tyre",
    "category": "bikes",
    "priceNow": 32,
    "priceWas": 62,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/schwalbe-one-tle-road-bike-tyre",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=182225&w=320&h=256"
  },
  {
    "id": 27,
    "title": "Craft CORE Bike Essence Wool Fietsshirt Lange Mouwen Roze Dames",
    "category": "bikes",
    "priceNow": 53,
    "priceWas": 100,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4205-001-N2509/medium/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames-1.webp"
  },
  {
    "id": 28,
    "title": "Craft CORE Bike Essence Wool Fietsshirt Lange Mouwen Roze Dames",
    "category": "bikes",
    "priceNow": 53,
    "priceWas": 100,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4205-001-N2509/medium/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames-1.webp"
  },
  {
    "id": 29,
    "title": "Craft CORE Bike Essence Wool Fietsshirt Lange Mouwen Roze Dames",
    "category": "bikes",
    "priceNow": 53,
    "priceWas": 100,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4205-001-N2509/medium/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames-1.webp"
  },
  {
    "id": 30,
    "title": "Craft CORE Bike Essence Wool Fietsshirt Lange Mouwen Roze Dames",
    "category": "bikes",
    "priceNow": 53,
    "priceWas": 100,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4205-001-N2509/medium/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames-1.webp"
  },
  {
    "id": 31,
    "title": "Craft CORE Bike Essence Wool Fietsshirt Lange Mouwen Roze Dames",
    "category": "bikes",
    "priceNow": 53,
    "priceWas": 100,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6030-4205-001-N2509/medium/craft-core-bike-essence-wool-fietsshirt-lange-mouwen-roze-dames-1.webp"
  },
  {
    "id": 32,
    "title": "GripGrab Classic High Cut Cycling Socks",
    "category": "clothing",
    "priceNow": 8,
    "priceWas": 15,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/gripgrab-summer-high-socks",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=103263&w=320&h=256"
  },
  {
    "id": 33,
    "title": "Castelli Squadra Stretch Wind Jacket",
    "category": "clothing",
    "priceNow": 43,
    "priceWas": 80,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/castelli-squadra-stretch",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=183211&w=320&h=256"
  },
  {
    "id": 34,
    "title": "Sportful Matchy W Cycling Jersey",
    "category": "clothing",
    "priceNow": 40,
    "priceWas": 75,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/sportful-matchy-w-jersey",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=191279&w=320&h=256"
  },
  {
    "id": 35,
    "title": "FYTS SNLST Thermo Fietsshirt Lange Mouwen Donkerrood Dames",
    "category": "bikes",
    "priceNow": 65,
    "priceWas": 120,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6911-0116-001-N2509/medium/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames-1.webp"
  },
  {
    "id": 36,
    "title": "FYTS SNLST Thermo Fietsshirt Lange Mouwen Donkerrood Dames",
    "category": "bikes",
    "priceNow": 65,
    "priceWas": 120,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6911-0116-001-N2509/medium/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames-1.webp"
  },
  {
    "id": 37,
    "title": "FYTS SNLST Thermo Fietsshirt Lange Mouwen Donkerrood Dames",
    "category": "bikes",
    "priceNow": 65,
    "priceWas": 120,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6911-0116-001-N2509/medium/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames-1.webp"
  },
  {
    "id": 38,
    "title": "FYTS SNLST Thermo Fietsshirt Lange Mouwen Donkerrood Dames",
    "category": "bikes",
    "priceNow": 65,
    "priceWas": 120,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6911-0116-001-N2509/medium/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames-1.webp"
  },
  {
    "id": 39,
    "title": "FYTS SNLST Thermo Fietsshirt Lange Mouwen Donkerrood Dames",
    "category": "bikes",
    "priceNow": 65,
    "priceWas": 120,
    "store": "Futurumshop",
    "storeUrl": "https://www.futurumshop.nl/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames.phtml",
    "added": "2026-04-13",
    "img": "https://assets.futurumshop.nl/fonl/img/Products/6911-0116-001-N2509/medium/fyts-snlst-thermo-fietsshirt-lange-mouwen-donkerrood-dames-1.webp"
  },
  {
    "id": 40,
    "title": "Craft Core 2-Pack W Base Layer Tops",
    "category": "accessories",
    "priceNow": 33,
    "priceWas": 60,
    "store": "Mantel",
    "storeUrl": "https://www.mantel.com/en/craft-core-2-pack-w",
    "added": "2026-04-13",
    "img": "https://cdn.mantel.com/images/product.php?image_id=174718&w=320&h=256"
  }
];
